name: Backend TypeScript Build (Bun)

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend-build.yml"
  pull_request:
    paths:
      - "backend/**"

jobs:
  build:
    name: Check TypeScript Compilation with Bun
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: TypeScript compile check
        run: bunx tsc --noEmit
